---
# tasks file for vmware-delete-snapshot
- name: Extract VM Name from inventory hostname
  set_fact:
    vm_name: "{{ inventory_hostname | regex_replace('_(([a-z]|[0-9]){8})\\-(([a-z]|[0-9]){4})\\-(([a-z]|[0-9]){4})\\-(([a-z]|[0-9]){4})\\-(([a-z]|[0-9]){12})', '') }}"

- name: print inventory hostname
  debug:
    var: vm_name

- name: Delete snapshot
    community.vmware.vmware_guest_snapshot:
    validate_certs: no
    datacenter: "{{ vm_datacenter }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    state: absent
    snapshot_name: ansible_preupdate_snapshot_{{ vm_name }}
  connection: local
  delegate_to: localhost
  become: false
