---
# tasks file for vmware_create_ESXI_tower_inventory
  - name: Get a list of all ESXi hosts
    vmware.vmware_rest.vcenter_host_info:
      vcenter_validate_certs: false
    register: my_hosts

  - name: Remove Existing ESXI inventory
    awx.awx.tower_inventory:
      name: "{{ inventory_name }}"
      description: "{{ inventory_desc }}"
      organization: "{{ inventory_org}}"
      state: absent

  - name: Add ESXI inventory tower inventory
    awx.awx.tower_inventory:
      name: "{{ inventory_name }}"
      description: "{{ inventory_desc }}"
      organization: "{{ inventory_org}}"
      state: present


  - name: Add ESXi hosts to tower inventory
    awx.awx.tower_host:
      name: "{{ item.name }}"
      description: "ESXi host imported from VCenter"
      inventory: "{{ inventory_name }}"
      state: present
      variables:
        connection_state: "{{ item.connection_state }}"
        host: "{{ item.host }}"
        power_state: "{{ item.power_state }}"
    loop: "{{ my_hosts.value }}"